# Generated by Django 3.2.16 on 2023-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_rename_offers_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='condition',
            field=models.BooleanField(default=False, verbose_name='Б/У'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(default=None, help_text='Желательно несколько фотографий с разных ракурсов', upload_to='images/', verbose_name='Фотография устройства'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='model',
            field=models.CharField(max_length=128, verbose_name='Модель устройства'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
